services:   
  exam_service:
    build:
      context: .
      dockerfile: ExamService/Dockerfile
    container_name: 'exam-service'
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development