services:   
  mongodb_test_service:
    image: mongo:4.4.6
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
        - "27017:27017"
  
  exam_service:
    build:
      context: .
      dockerfile: ExamService/Dockerfile
    depends_on:
      - mongodb_test_service
    container_name: 'exam-service'
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development