using AutoMapper;
using EsamiOnline.Exam;
using EsamiOnline.Models;

namespace EsamiOnline.Mappers;

public class ExamMappingProfile : Profile
{
    public ExamMappingProfile()
    {
        // Map ExamRequest to ExamEntity
        CreateMap<ExamRequest, ExamEntity>()
            .ForMember(dest => dest.Id, opt => opt.Ignore()); // Assuming Id is generated by the database

        // Map ExamEntity to ExamReply
        CreateMap<ExamEntity, ExamReply>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.Message, opt => opt.MapFrom(src => src.Name));

        // Map ExamEntity to ExamRequest (reverse mapping)
        CreateMap<ExamEntity, ExamRequest>()
            .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name));

        // Map ExamReply to ExamEntity (reverse mapping)
        CreateMap<ExamReply, ExamEntity>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Message));
    }
}